'use strict';
const SUPABASE_URL='https://ltxrycmreumoqfpcbwnb.supabase.co';
const SUPABASE_KEY='sb_publishable_wdc4ImKB1f0Q-v4Po9DOwA_xIpPXHkh';
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let allOrders=[];let currentFilter='all';let currentSource='all';
const ORDER_STATUSES=['new','confirmed','processing','packed','shipped','delivered','cancelled','returned'];
function escapeHtml(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function money(v){const n=Number(v||0);return Number.isFinite(n)?`₹${n.toLocaleString('en-IN',{minimumFractionDigits:0,maximumFractionDigits:2})}`:'₹0'}
function normalizeStatus(v){return String(v||'new').toLowerCase()}
function statusLabel(v){return String(v||'new').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function statusClass(v){return `s-${normalizeStatus(v)}`}
function dateTime(v){if(!v)return'—';const d=new Date(v);if(Number.isNaN(d.getTime()))return escapeHtml(v);return d.toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}
function isConfirmed(o){return ['confirmed','processing','packed','shipped','delivered'].includes(normalizeStatus(o.order_status))}
async function loadOrders(){const c=document.getElementById('orders');if(!c)return;c.innerHTML='<div class="loading">Loading orders...</div>';try{const{data,error}=await supabaseClient.from('orders').select('id,order_number,gateway,gateway_order_id,gateway_payment_id,payment_status,order_status,currency,subtotal,discount,shipping_fee,tax,total,coupon_code,customer_name,customer_email,customer_phone,address_line1,address_line2,city,state,postal_code,country,notes,source,medium,campaign,landing_page,referrer,session_id,created_at,updated_at,invoice_number,tracking_number,tracking_url,payment_method,billing_address,shipping_address').order('created_at',{ascending:false});if(error)throw error;allOrders=Array.isArray(data)?data:[];updateStats();renderOrders()}catch(e){console.error(e);c.innerHTML=`<div class="error"><strong>Unable to load orders.</strong><br><br>${escapeHtml(e.message||'Unknown error')}<br><br><button class="btn" onclick="loadOrders()">Try Again</button></div>`}}
function updateStats(){const confirmed=allOrders.filter(isConfirmed);document.getElementById('total').textContent=allOrders.length;document.getElementById('pending').textContent=allOrders.filter(o=>normalizeStatus(o.order_status)==='new').length;document.getElementById('confirmed').textContent=confirmed.length;document.getElementById('delivered').textContent=allOrders.filter(o=>normalizeStatus(o.order_status)==='delivered').length;document.getElementById('revenue').textContent=money(confirmed.reduce((s,o)=>s+Number(o.total||0),0));document.getElementById('waRevenue').textContent=money(confirmed.filter(o=>String(o.source||'').toLowerCase()==='whatsapp').reduce((s,o)=>s+Number(o.total||0),0))}
function getSearchValue(){return String(document.getElementById('search')?.value||'').trim().toLowerCase()}
function rangeMatches(o){const r=document.getElementById('reportRange')?.value||'all';if(r==='all')return true;const d=new Date(o.created_at),now=new Date();if(Number.isNaN(d.getTime()))return false;if(r==='today')return d.toDateString()===now.toDateString();if(r==='month')return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();return d>=new Date(Date.now()-Number(r)*86400000)}
function filteredOrders(){const q=getSearchValue();return allOrders.filter(o=>{const st=normalizeStatus(o.order_status),src=String(o.source||'website').toLowerCase();if(currentFilter!=='all'&&st!==currentFilter)return false;if(currentSource!=='all'&&src!==currentSource)return false;if(q){const s=[o.order_number,o.customer_name,o.customer_email,o.customer_phone,o.payment_status,o.order_status,o.city,o.state,o.postal_code,o.tracking_number,o.invoice_number,o.source].filter(Boolean).join(' ').toLowerCase();if(!s.includes(q))return false}return true})}
function renderOrders(){const c=document.getElementById('orders');if(!c)return;const orders=filteredOrders();if(!orders.length){c.innerHTML='<div class="empty"><strong>No orders found.</strong><br><br>Try changing the search or filter.</div>';return}c.innerHTML=`<div class="wrap"><table><thead><tr><th>ORDER</th><th>CUSTOMER</th><th>SOURCE</th><th>DATE</th><th>PAYMENT</th><th>STATUS</th><th>TOTAL</th><th>ACTION</th></tr></thead><tbody>${orders.map(renderOrderRow).join('')}</tbody></table></div>`}
function renderOrderRow(o){const st=normalizeStatus(o.order_status),pay=String(o.payment_status||'pending').toLowerCase(),confirmed=isConfirmed(o);return `<tr><td><strong>${escapeHtml(o.order_number||'Order')}</strong><div class="small">${escapeHtml(o.id||'')}</div></td><td><strong>${escapeHtml(o.customer_name||'Guest Customer')}</strong><div class="small">${escapeHtml(o.customer_phone||'')}</div><div class="small">${escapeHtml(o.customer_email||'')}</div></td><td><span class="source">${escapeHtml(o.source||'website')}</span></td><td>${dateTime(o.created_at)}</td><td><span class="status ${pay==='paid'?'s-delivered':pay==='failed'?'s-cancelled':'s-pending'}">${escapeHtml(pay)}</span><div class="small">${escapeHtml(o.payment_method||'')}</div></td><td><span class="status ${statusClass(st)}">${escapeHtml(statusLabel(st))}</span></td><td><strong>${money(o.total)}</strong>${confirmed?'<div class="confirm-note">Counts in sales</div>':''}</td><td><button class="btn" onclick="openOrder('${escapeHtml(o.id)}')">View</button>${st==='new'?` <button class="btn green" onclick="confirmOrder('${escapeHtml(o.id)}')">Confirm</button>`:''} <button class="btn red" onclick="deleteOrder('${escapeHtml(o.id)}')">Delete</button></td></tr>`}
async function confirmOrder(id){const o=allOrders.find(x=>String(x.id)===String(id));if(!o)return;if(!confirm(`Confirm ${o.order_number||'this order'}?\n\nOnly confirmed orders are counted in sales reports.`))return;const{error}=await supabaseClient.from('orders').update({order_status:'confirmed',updated_at:new Date().toISOString()}).eq('id',id);if(error){alert('Could not confirm order: '+error.message);return}await loadOrders()}
async function deleteOrder(id){const o=allOrders.find(x=>String(x.id)===String(id));if(!o)return;if(!confirm(`DELETE ${o.order_number||'this order'}?\n\nThis is permanent and is intended for test/mistake orders.`))return;const{error}=await supabaseClient.from('orders').delete().eq('id',id);if(error){alert('Could not delete order: '+error.message);return}closeModal();await loadOrders()}
async function openOrder(id){const o=allOrders.find(x=>String(x.id)===String(id));if(!o)return;document.getElementById('title').textContent=o.order_number||'Order Details';document.getElementById('body').innerHTML=`<div class="notice">${isConfirmed(o)?'This order is CONFIRMED and counts in sales reports.':'This order is NOT confirmed and does not count in sales reports.'}</div><div class="actions"><button class="invoice" onclick="printInvoice('${escapeHtml(o.id)}')">Invoice / Print</button>${o.customer_phone?`<button class="wa" onclick="openWhatsApp('${escapeHtml(o.id)}')">WhatsApp Customer</button>`:''}${normalizeStatus(o.order_status)==='new'?`<button class="btn green" onclick="confirmOrder('${escapeHtml(o.id)}');closeModal()">Confirm Order</button>`:''}<button class="btn red" onclick="deleteOrder('${escapeHtml(o.id)}')">Delete Order</button></div><div class="grid"><div class="info"><h3>CUSTOMER</h3><p><strong>${escapeHtml(o.customer_name||'Guest Customer')}</strong><br>${escapeHtml(o.customer_email||'No email')}<br>${escapeHtml(o.customer_phone||'No phone')}</p></div><div class="info"><h3>ORDER TOTAL</h3><p>Subtotal: ${money(o.subtotal)}<br>Discount: ${money(o.discount)}<br>Shipping: ${money(o.shipping_fee)}<br>Tax: ${money(o.tax)}<br><br><strong>Total: ${money(o.total)}</strong></p></div><div class="info"><h3>PAYMENT</h3><p>Status: <strong>${escapeHtml(o.payment_status||'pending')}</strong><br>Method: ${escapeHtml(o.payment_method||'—')}<br>Gateway: ${escapeHtml(o.gateway||'—')}</p></div><div class="info"><h3>SOURCE</h3><p>${escapeHtml(o.source||'website')} ${o.medium?`/ ${escapeHtml(o.medium)}`:''}<br>${escapeHtml(o.campaign||'')}</p></div><div class="info"><h3>SHIPPING ADDRESS</h3><p>${escapeHtml(o.customer_name||'')}<br>${escapeHtml(o.address_line1||'')}${o.address_line2?`<br>${escapeHtml(o.address_line2)}`:''}<br>${escapeHtml(o.city||'')}${o.city&&o.state?', ':''}${escapeHtml(o.state||'')}${o.postal_code?`<br>${escapeHtml(o.postal_code)}`:''}${o.country?`<br>${escapeHtml(o.country)}`:''}</p></div><div class="info"><h3>NOTES</h3><p>${escapeHtml(o.notes||'—')}</p></div></div><div style="margin-top:20px"><h3>Order Status</h3><select id="statusSelect">${ORDER_STATUSES.map(s=>`<option value="${s}" ${s===normalizeStatus(o.order_status)?'selected':''}>${escapeHtml(statusLabel(s))}</option>`).join('')}</select><button class="update" onclick="updateOrderStatus('${escapeHtml(o.id)}')">Update Order Status</button></div><div style="margin-top:25px"><h3>Tracking</h3><div class="tracking"><input id="trackingNumber" placeholder="Tracking number" value="${escapeHtml(o.tracking_number||'')}"><input id="trackingUrl" placeholder="Tracking URL" value="${escapeHtml(o.tracking_url||'')}"></div><button class="update" onclick="updateTracking('${escapeHtml(o.id)}')">Save Tracking</button></div>`;document.getElementById('modal').classList.add('open')}
function closeModal(){document.getElementById('modal').classList.remove('open')}
async function updateOrderStatus(id){const status=document.getElementById('statusSelect')?.value;if(!status)return;const{error}=await supabaseClient.from('orders').update({order_status:status,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert('Could not update status: '+error.message);return}closeModal();await loadOrders()}
async function updateTracking(id){const tracking_number=document.getElementById('trackingNumber')?.value.trim()||null,tracking_url=document.getElementById('trackingUrl')?.value.trim()||null;const{error}=await supabaseClient.from('orders').update({tracking_number,tracking_url,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert('Could not save tracking: '+error.message);return}alert('Tracking saved.');await loadOrders()}
function openWhatsApp(id){const o=allOrders.find(x=>String(x.id)===String(id));if(!o?.customer_phone)return;const phone=String(o.customer_phone).replace(/\D/g,'');window.open(`https://wa.me/${phone}?text=${encodeURIComponent(`Hi ${o.customer_name||''}, this is Trends by AK regarding order ${o.order_number||''}.`)}`,'_blank')}
function openWhatsAppOrderModal(){document.getElementById('waModal').classList.add('open')}
function closeWhatsAppOrderModal(){document.getElementById('waModal').classList.remove('open')}
function clearWhatsAppForm(){['waName','waPhone','waEmail','waAmount','waProducts','waNotes'].forEach(id=>{const e=document.getElementById(id);if(e)e.value=''});document.getElementById('waPayment').value='pending';document.getElementById('waMethod').value='WhatsApp'}
async function saveWhatsAppOrder(){const name=document.getElementById('waName').value.trim(),phone=document.getElementById('waPhone').value.trim(),email=document.getElementById('waEmail').value.trim(),amount=Number(document.getElementById('waAmount').value),payment=document.getElementById('waPayment').value,method=document.getElementById('waMethod').value,products=document.getElementById('waProducts').value.trim(),notes=document.getElementById('waNotes').value.trim();if(!name||!Number.isFinite(amount)||amount<0){alert('Please enter customer name and a valid order amount.');return}const orderNumber='WA-'+Date.now().toString().slice(-8);const{error}=await supabaseClient.from('orders').insert({order_number:orderNumber,gateway:'manual',payment_status:payment,order_status:'new',currency:'INR',subtotal:amount,discount:0,shipping_fee:0,tax:0,total:amount,customer_name:name,customer_email:email||null,customer_phone:phone||null,notes:[products?`Products: ${products}`:'',notes].filter(Boolean).join('\n'),source:'whatsapp',medium:'whatsapp',payment_method:method,created_at:new Date().toISOString(),updated_at:new Date().toISOString()});if(error){alert('Could not save WhatsApp order: '+error.message);return}closeWhatsAppOrderModal();clearWhatsAppForm();await loadOrders();alert(`${orderNumber} saved as New / Pending. Confirm it when the customer has confirmed the order.`)}
function csvEscape(v){return`"${String(v??'').replace(/"/g,'""')}"`}
function downloadReport(){const orders=filteredOrders().filter(rangeMatches);if(!orders.length){alert('No orders match the selected report filters.');return}const rows=[['Order Number','Date','Customer','Phone','Source','Status','Payment Status','Payment Method','Amount','Confirmed Sale']];orders.forEach(o=>rows.push([o.order_number,dateTime(o.created_at),o.customer_name,o.customer_phone,o.source||'website',o.order_status,o.payment_status,o.payment_method,o.total,isConfirmed(o)?'Yes':'No']));const csv=rows.map(r=>r.map(csvEscape).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`trends-by-ak-orders-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function printInvoice(id){const o=allOrders.find(x=>String(x.id)===String(id));if(!o)return;const w=window.open('','_blank');if(!w)return;w.document.write(`<html><head><title>${escapeHtml(o.order_number||'Invoice')}</title><style>body{font-family:Arial;padding:35px;color:#222}table{width:100%;border-collapse:collapse;margin-top:25px}td{padding:9px;border-bottom:1px solid #ddd}</style></head><body><h1>Trends by AK</h1><div>Sustainable Luxury but affordable</div><h2>Order ${escapeHtml(o.order_number||'')}</h2><p>${dateTime(o.created_at)}</p><p><strong>Customer:</strong> ${escapeHtml(o.customer_name||'')}<br>${escapeHtml(o.customer_phone||'')}<br>${escapeHtml(o.customer_email||'')}</p><table><tr><td>Subtotal</td><td>${money(o.subtotal)}</td></tr><tr><td>Discount</td><td>${money(o.discount)}</td></tr><tr><td>Shipping</td><td>${money(o.shipping_fee)}</td></tr><tr><td>Tax</td><td>${money(o.tax)}</td></tr><tr><td><strong>Total</strong></td><td><strong>${money(o.total)}</strong></td></tr></table><p>Source: ${escapeHtml(o.source||'website')} | Status: ${escapeHtml(o.order_status||'new')}</p></body></html>`);w.document.close();w.focus();w.print()}
function setup(){document.getElementById('search').addEventListener('input',renderOrders);document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.status||'all';currentSource=b.dataset.source||'all';if(b.dataset.source)currentFilter='all';renderOrders()}));document.getElementById('reportRange').addEventListener('change',renderOrders);document.getElementById('waModal').addEventListener('click',e=>{if(e.target.id==='waModal')closeWhatsAppOrderModal()});document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});loadOrders()}
document.addEventListener('DOMContentLoaded',setup);
